# Generated by Django 6.0.3 on 2026-03-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('service', models.CharField(blank=True, choices=[('lead_generation', 'Лидогенерация'), ('call_center', 'Call-центр'), ('avito', 'Авито'), ('recruiting', 'Рекрутинг'), ('lead_code', 'Лид-КОД'), ('complex', 'Комплекс'), ('other', 'Другое')], max_length=50, verbose_name='Услуга')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'В работе'), ('converted', 'Успешно'), ('rejected', 'Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('position', models.CharField(choices=[('manager', 'Менеджер по продажам'), ('call_operator', 'Оператор call-центра'), ('recruiter', 'Рекрутер'), ('info_collector', 'Сборщик информации'), ('other', 'Другое')], max_length=50, verbose_name='Должность')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
